adw_common:
#    doctrine_table_prefix: %my_awesome_table_prefix% # Префикс для названий таблиц
    response_headers: # Дефолтные заголовки для ответов
        X-Frame-Options: deny
        X-Content-Type-Options: nosniff

monolog:
    channels: [domain]
    handlers:
        domain:
            type:  rotating_file
            path:  "%kernel.logs_dir%/domain/%kernel.environment%.log"
            level: info