stages:
  - test
  - test_php71

variables:
  MYSQL_DATABASE: "database"
  MYSQL_ROOT_PASSWORD: "database_password"
  SYMFONY__DATABASE__HOST: "mysql"
  SYMFONY__DATABASE__NAME: "database"
  SYMFONY__DATABASE__PASSWORD: "database_password"
  SYMFONY__DATABASE__PORT: "null"
  SYMFONY__DATABASE__USER: "root"
  COMPOSER_CACHE_DIR: "/cache/php-composer"
  NPM_CONFIG_CACHE: "/cache/node-npm"
  BUNDLE_PATH: "/cache/ruby-gems"

before_script:
  - rm -f /usr/local/etc/php/conf.d/xdebug.ini
  - echo 'date.timezone=Europe/Moscow' >> /usr/local/etc/php/conf.d/extra.ini
  - echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/extra.ini

security_check:
  stage: test
  image: kolyadin/php:71
  allow_failure: false
  script:
    - composer install --profile --prefer-dist -n
    - ./vendor/bin/security-checker security:check
  cache: {}

phpunit_71_55:
  stage: test_php71
  image: kolyadin/php:71
  allow_failure: false
  services:
    - mysql:5.5
  script:
    - composer install --profile --prefer-dist -n
    - ./bin/setup-test.sh
    - ./vendor/bin/simple-phpunit
  cache: {}

phpunit_71_56:
  stage: test_php71
  image: kolyadin/php:71
  allow_failure: false
  services:
  - mysql:5.6
  script:
  - composer install --profile --prefer-dist -n
  - ./bin/setup-test.sh
  - ./vendor/bin/simple-phpunit
  cache: {}

phpunit_71_57:
  stage: test_php71
  image: kolyadin/php:71
  allow_failure: false
  services:
  - mysql:5.7
  script:
  - composer install --profile --prefer-dist -n
  - ./bin/setup-test.sh
  - ./vendor/bin/simple-phpunit
  cache: {}