version: '3.7'

services:
  php:
    build: ./.docker/php
    image: php7.2
    ports:
      - '9000:9000'
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
      - ./.docker/php/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/fpm/php-fpm.conf:/usr/local/etc/php/7.2/fpm/php-fpm.conf
    networks:
      - code-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - code-network

  mysql:
    image: mysql:5.7
    command: --sql_mode=""
    volumes:
      - dbdata:/var/lib/mysql
      - ./.docker/mysql-dumps/:/mysql-dumps/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
    networks:
      - code-network

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080
#    networks:
#      - code-network

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.8
#    environment:
#      PMA_HOST: database
#      PMA_PORT: 3306
#      PMA_USER: root
#      PMA_PASSWORD: root
#    ports:
#      - 8081:80
#    networks:
#      - code-network

volumes:
  dbdata:

networks:
  code-network:
    driver: bridge